# Generated by Django 3.2.4 on 2021-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=13)),
                ('description', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('bedrooms', models.TextField(blank=True)),
                ('bathrooms', models.TextField(blank=True)),
                ('garage', models.TextField(blank=True)),
                ('sqft', models.TextField(blank=True)),
                ('lot_size', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('HS', 'House'), ('LND', 'Land'), ('OFC', 'Office')], default='HS', max_length=10)),
                ('status', models.CharField(choices=[('SL', 'sale'), ('RNT', 'rent')], default='RNT', max_length=10)),
                ('photo_main', models.ImageField(upload_to='listings')),
                ('photo_1', models.ImageField(upload_to='listings')),
                ('photo_2', models.ImageField(upload_to='listings')),
                ('photo_3', models.ImageField(upload_to='listings')),
                ('photo_4', models.ImageField(upload_to='listings')),
                ('photo_5', models.ImageField(upload_to='listings')),
                ('photo_6', models.ImageField(upload_to='listings')),
                ('is_published', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
