# Generated by Django 3.2.4 on 2021-06-22 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0004_alter_listing_photo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
            preserve_default=False,
        ),
    ]
