# Generated by Django 3.2.4 on 2021-06-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Office', 'Office')], default='HS', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], default='RNT', max_length=10),
        ),
    ]
