counties={
    'Nairobi': 'Nairobi',
    'Mombasa': 'Mombasa',
    'Lamu': 'Lamu',
    'Kwale': 'Kwale',
    'Kilifi': 'Kilifi',
    'Kiambu': 'Kiambu',
    'Nakuru': 'Nakuru',
    'Tana River' : 'Tana River',
    'Taita/Taveta' :'Taita/Taveta',
    'Garissa ':'Garissa ',
    'Wajir ':'Wajir ',
    'Mandera':'Mandera',
    'Marsabit':'Marsabit',
    'Isiolo':'Isiolo',
    'Meru':'Meru',
    'Tharaka-Nithi':'Tharaka-Nithi',
    'Embu':'Embu',
    'Kitui':'Kitui',
    'Machakos':'Machakos',
    'Makueni':'Makueni',
    'Nyandarua':'Nyandarua',
    'Nyeri':'Nyeri',
    'Kirinyaga':'Kirinyaga',
    'Muranga':'Muranga',
    'Turkana':'Turkana',
    'West Pokot':'West Pokot',
    'Samburu':'Samburu',
    'Trans Nzoia':'Trans Nzoia',
    'Uasin Gishu':'Uasin Gishu',
    'Elgeyo/Marakwet':'Elgeyo/Marakwet',
    'Nandi':'Nandi',
    'Baringo':'Baringo',
    'Laikipia':'Laikipia',
    'Nakuru':'Nakuru',
    'Narok':'Narok',
    'Kajiado':'Kajiado',
    'Kericho':'Kericho',
    'Bomet':'Bomet',
    'Kakamega':'Kakamega',
    'Vihiga':'Vihiga',
    'Bungoma':'Bungoma',
    'Busia':'Busia',
    'Siaya':'Siaya',
    'Kisumu':'Kisumu',
    'Homa Bay':'Homa Bay',
    'Migori':'Migori',
    'Kisii':'Kisii',
    'Nyamira':'Nyamira',
    
}
area={
    
}